### ISSUE TITLE
won't activate

### ISSUE THREAD

**Issue by dkebler** [jessexknight/atom-filter-lines#2]
using atom 1.32.1 on linux ubuntu 18.04

1. I select some text
2.  try key combo cntrl+alt+f or go to command from palette and run it.

Nothing happens.

Either I am missing some info on how to use it or it's not working in this version of atom.

**Comment by dkebler** [comment]
Ok, key combo doesn't work but if I bring up command palette from keyboard and not mouse it does.

So probably just a conflict with key combo.

**Comment by jessexknight** [comment]
The [keybinding resolver](https://atom.io/packages/keybinding-resolver) might help resolve the conflict :)

`CTRL`+`.`
