### ISSUE TITLE
Select Filtered

### ISSUE THREAD

**Issue by dkebler** [jessexknight/atom-filter-lines#3]
Would be nice if after filtering the filtered lines could be selected easily  (a variant of cntrl-a).  As it is I have to carefully not select the first line and the last symbol of the last line as those represent the filtered lines.  Thx for your efforts!

**Comment by jessexknight** [comment]
I'm not quite sure what you mean. Can you post the content you're filtering and perhaps a screenshot showing: the desired selection vs result of ctrl+a?

**Comment by jessexknight** [comment]
In abc798f, I've added a new keymap which allows you to "filter-and-select" :)

Let me know if that works for you.
