### ISSUE TITLE
Allow user to copy the filtered lines

### ISSUE THREAD

**Issue by kniyer70** [jessexknight/atom-filter-lines#4]
The filter returned all the required lines I wanted to see but when I tried to copy it, I was unable to copy the finite set of filtered lines returned. It would be nice if we could copy these filtered lines to clipboard. Alternatively, while using a similar feature in a different editor, it was filtering the file to a separate tab without touching the existing file that was being edited so this way you could keep creating tabs with different filter keys that can prove very useful when we are cross comparing things within the same log file.

I hope I conveyed what I was looking for and I believe it will be a great feature addition to your existing package. Hope to see this added soon.

**Comment by jessexknight** [comment]
Thanks for the detailed request. I've added a "filter-and-select" keymap in abc798f. This should allow you to copy the selected filtering result, and do whatever you want with it from there, including copy to a new file.
